# Form implementation generated from reading ui file 'login_or_signup.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from fnmatch import *

from db import log_in, sign_up


class Ui_MainWindow(object):
    cnt_show, cnt_show1, cnt_show2 = 0, 0, 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(374, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "    background-color: #25273e;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -30, 374, 630))
        font = QtGui.QFont()
        font.setFamily("Revard")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
                                     "    border: 1px;\n"
                                     "    background-color: #25273e;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab {\n"
                                     "    color: rgb(202, 204, 213);\n"
                                     "    margin-left: 1px;\n"
                                     "    padding-top: 5px;\n"
                                     "    min-width: 30ex;\n"
                                     "    min_heigth: 20ex;\n"
                                     "    background-color: rgb(86, 91, 145);\n"
                                     "    left: -1px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:selected {\n"
                                     "    background-color: #25273e;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:hover {\n"
                                     "    background-color: rgb(61, 65, 103);\n"
                                     "}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Salwey")
        font.setPointSize(8)
        self.tab.setFont(font)
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.show_pass_1 = QtWidgets.QPushButton(parent=self.tab)
        self.show_pass_1.setGeometry(QtCore.QRect(300, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.show_pass_1.setFont(font)
        self.show_pass_1.setStyleSheet("color: #a2a5b6;\n"
                                       "background-color: #25273e;\n"
                                       "border: 0px")
        self.show_pass_1.setObjectName("show_pass_1")
        self.show_pass_1.clicked.connect(lambda: self.show_password_func(1))
        self.label_ques = QtWidgets.QLabel(parent=self.tab)
        self.label_ques.setGeometry(QtCore.QRect(60, 560, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.label_ques.setFont(font)
        self.label_ques.setStyleSheet("color: #b7b9c2")
        self.label_ques.setObjectName("label_ques")
        self.line_username = QtWidgets.QLineEdit(parent=self.tab)
        self.line_username.setGeometry(QtCore.QRect(20, 150, 334, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.line_username.setFont(font)
        self.line_username.setStyleSheet("QLineEdit {\n"
                                         "    padding-left: 10px;\n"
                                         "    border: 2px solid #533e5a;\n"
                                         "    border-radius: 15px;\n"
                                         "    background-color: rgb(37, 39, 62);\n"
                                         "    color: rgb(255, 255, 255)\n"
                                         "}\n"
                                         "\n"
                                         "QLineEdit::focus, active {\n"
                                         "    background-color: rgb(37, 39, 62);\n"
                                         "    color: rgb(198, 198, 198)\n"
                                         "}\n"
                                         "\n"
                                         "")
        self.line_username.setInputMask("")
        self.line_username.setText("")
        self.line_username.setMaxLength(24)
        self.line_username.setFrame(True)
        self.line_username.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.line_username.setDragEnabled(False)
        self.line_username.setClearButtonEnabled(False)
        self.line_username.setObjectName("line_username")
        self.line_password = QtWidgets.QLineEdit(parent=self.tab)
        self.line_password.setGeometry(QtCore.QRect(20, 210, 334, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.line_password.setFont(font)
        self.line_password.setStyleSheet("QLineEdit {\n"
                                         "    padding-left: 10px;\n"
                                         "    border: 2px solid #533e5a;\n"
                                         "    border-radius: 15px;\n"
                                         "    background-color: rgb(37, 39, 62);\n"
                                         "    color: rgb(255, 255, 255)\n"
                                         "}\n"
                                         "\n"
                                         "QLineEdit::focus, active {\n"
                                         "    background-color: rgb(37, 39, 62);\n"
                                         "    color: rgb(198, 198, 198)\n"
                                         "}")
        self.line_password.setMaxLength(20)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_password.setObjectName("line_password")
        self.checkBox_rememb = QtWidgets.QCheckBox(parent=self.tab)
        self.checkBox_rememb.setGeometry(QtCore.QRect(40, 270, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(13)
        self.checkBox_rememb.setFont(font)
        self.checkBox_rememb.setStyleSheet("QCheckBox {\n"
                                           "    color: #a2a5b6;\n"
                                           "}\n"
                                           "\n"
                                           "QCheckBox::indicator:unchecked {\n"
                                           "    border: 1px solid white;\n"
                                           "    background-color: #25273e\n"
                                           "}\n"
                                           "")
        self.checkBox_rememb.setObjectName("checkBox_rememb")
        self.btn_forgot = QtWidgets.QPushButton(parent=self.tab)
        self.btn_forgot.setGeometry(QtCore.QRect(190, 268, 151, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_forgot.setFont(font)
        self.btn_forgot.setStyleSheet("color: rgb(167, 71, 112);\n"
                                      "background-color: #25273e;\n"
                                      "border: 0px")
        self.btn_forgot.setObjectName("btn_forgot")
        self.label_log_in = QtWidgets.QLabel(parent=self.tab)
        self.label_log_in.setGeometry(QtCore.QRect(20, 40, 160, 80))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(35)
        font.setBold(False)
        font.setWeight(50)
        self.label_log_in.setFont(font)
        self.label_log_in.setStyleSheet("color: rgb(202, 204, 213)")
        self.label_log_in.setObjectName("label_log_in")
        self.btn_log_in = QtWidgets.QPushButton(parent=self.tab)
        self.btn_log_in.setGeometry(QtCore.QRect(80, 340, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.btn_log_in.setFont(font)
        self.btn_log_in.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_log_in.setStyleSheet("border-radius: 10px;\n"
                                      "text-align: center;\n"
                                      "color: rgb(252, 229, 240);\n"
                                      "background-color: rgb(238, 58, 87)")
        self.btn_log_in.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.btn_log_in.setAutoDefault(False)
        self.btn_log_in.setDefault(False)
        self.btn_log_in.setObjectName("btn_log_in")
        self.btn_log_in.clicked.connect(self.log_in_check)
        self.btn_ques_sign_up = QtWidgets.QPushButton(parent=self.tab)
        self.btn_ques_sign_up.setGeometry(QtCore.QRect(230, 560, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.btn_ques_sign_up.setFont(font)
        self.btn_ques_sign_up.setStyleSheet("color: rgb(167, 71, 112);\n"
                                            "background-color: #25273e;\n"
                                            "border: 0px")
        self.btn_ques_sign_up.setObjectName("btn_ques_sign_up")
        self.btn_ques_sign_up.clicked.connect(self.switch_tab)
        self.label_error_tab = QtWidgets.QLabel(parent=self.tab)
        self.label_error_tab.setGeometry(QtCore.QRect(30, 120, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Inglobal")
        font.setPointSize(12)
        font.setBold(True)
        self.label_error_tab.setFont(font)
        self.label_error_tab.setStyleSheet("color: rgb(204, 118, 120)")
        self.label_error_tab.setObjectName("label_error")
        self.label_error_tab.raise_()
        self.line_username.raise_()
        self.checkBox_rememb.raise_()
        self.line_password.raise_()
        self.btn_forgot.raise_()
        self.label_log_in.raise_()
        self.btn_log_in.raise_()
        self.btn_ques_sign_up.raise_()
        self.label_ques.raise_()
        self.show_pass_1.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line_username_2 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.line_username_2.setGeometry(QtCore.QRect(20, 140, 161, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.line_username_2.setFont(font)
        self.line_username_2.setStyleSheet("QLineEdit {\n"
                                           "    padding-left: 10px;\n"
                                           "    border: 2px solid #533e5a;\n"
                                           "    border-radius: 15px;\n"
                                           "    background-color: rgb(37, 39, 62);\n"
                                           "    color: rgb(255, 255, 255)\n"
                                           "}\n"
                                           "\n"
                                           "QLineEdit::focus, active {\n"
                                           "    background-color: rgb(37, 39, 62);\n"
                                           "    color: rgb(198, 198, 198)\n"
                                           "}\n"
                                           "\n"
                                           "")
        self.line_username_2.setInputMask("")
        self.line_username_2.setText("")
        self.line_username_2.setMaxLength(24)
        self.line_username_2.setFrame(True)
        self.line_username_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.line_username_2.setDragEnabled(False)
        self.line_username_2.setClearButtonEnabled(False)
        self.line_username_2.setObjectName("line_username_2")
        self.line_phone = QtWidgets.QLineEdit(parent=self.tab_2)
        self.line_phone.setGeometry(QtCore.QRect(190, 140, 161, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.line_phone.setFont(font)
        self.line_phone.setStyleSheet("QLineEdit {\n"
                                      "    padding-left: 10px;\n"
                                      "    border: 2px solid #533e5a;\n"
                                      "    border-radius: 15px;\n"
                                      "    background-color: rgb(37, 39, 62);\n"
                                      "    color: rgb(255, 255, 255)\n"
                                      "}\n"
                                      "\n"
                                      "QLineEdit::focus, active {\n"
                                      "    background-color: rgb(37, 39, 62);\n"
                                      "    color: rgb(198, 198, 198)\n"
                                      "}\n"
                                      "\n"
                                      "")
        self.line_phone.setInputMask("")
        self.line_phone.setText("")
        self.line_phone.setMaxLength(11)
        self.line_phone.setFrame(True)
        self.line_phone.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.line_phone.setDragEnabled(False)
        self.line_phone.setClearButtonEnabled(False)
        self.line_phone.setObjectName("line_phone")
        self.line_email = QtWidgets.QLineEdit(parent=self.tab_2)
        self.line_email.setGeometry(QtCore.QRect(20, 190, 334, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.line_email.setFont(font)
        self.line_email.setStyleSheet("QLineEdit {\n"
                                      "    padding-left: 10px;\n"
                                      "    border: 2px solid #533e5a;\n"
                                      "    border-radius: 15px;\n"
                                      "    background-color: rgb(37, 39, 62);\n"
                                      "    color: rgb(255, 255, 255)\n"
                                      "}\n"
                                      "\n"
                                      "QLineEdit::focus, active {\n"
                                      "    background-color: rgb(37, 39, 62);\n"
                                      "    color: rgb(198, 198, 198)\n"
                                      "}\n"
                                      "\n"
                                      "")
        self.line_email.setInputMask("")
        self.line_email.setText("")
        self.line_email.setMaxLength(25)
        self.line_email.setFrame(True)
        self.line_email.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.line_email.setDragEnabled(False)
        self.line_email.setClearButtonEnabled(False)
        self.line_email.setObjectName("line_email")
        self.line_password_2 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.line_password_2.setGeometry(QtCore.QRect(20, 240, 334, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.line_password_2.setFont(font)
        self.line_password_2.setStyleSheet("QLineEdit {\n"
                                           "    padding-left: 10px;\n"
                                           "    border: 2px solid #533e5a;\n"
                                           "    border-radius: 15px;\n"
                                           "    background-color: rgb(37, 39, 62);\n"
                                           "    color: rgb(255, 255, 255)\n"
                                           "}\n"
                                           "\n"
                                           "QLineEdit::focus, active {\n"
                                           "    background-color: rgb(37, 39, 62);\n"
                                           "    color: rgb(198, 198, 198)\n"
                                           "}")
        self.line_password_2.setMaxLength(20)
        self.line_password_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_password_2.setObjectName("line_password_2")
        self.line_confirm_password = QtWidgets.QLineEdit(parent=self.tab_2)
        self.line_confirm_password.setGeometry(QtCore.QRect(20, 290, 334, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.line_confirm_password.setFont(font)
        self.line_confirm_password.setStyleSheet("QLineEdit {\n"
                                                 "    padding-left: 10px;\n"
                                                 "    border: 2px solid #533e5a;\n"
                                                 "    border-radius: 15px;\n"
                                                 "    background-color: rgb(37, 39, 62);\n"
                                                 "    color: rgb(255, 255, 255)\n"
                                                 "}\n"
                                                 "\n"
                                                 "QLineEdit::focus, active {\n"
                                                 "    background-color: rgb(37, 39, 62);\n"
                                                 "    color: rgb(198, 198, 198)\n"
                                                 "}")
        self.line_confirm_password.setMaxLength(20)
        self.line_confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_confirm_password.setObjectName("line_confirm_password")
        self.checkBox_agree = QtWidgets.QCheckBox(parent=self.tab_2)
        self.checkBox_agree.setGeometry(QtCore.QRect(40, 340, 301, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        self.checkBox_agree.setFont(font)
        self.checkBox_agree.setStyleSheet("QCheckBox {\n"
                                          "    color: #a2a5b6;\n"
                                          "}\n"
                                          "\n"
                                          "QCheckBox::indicator:unchecked {\n"
                                          "    border: 1px solid white;\n"
                                          "    background-color: #25273e\n"
                                          "}\n"
                                          "")
        self.checkBox_agree.setObjectName("checkBox_agree")
        self.btn_show_conf_pas = QtWidgets.QPushButton(parent=self.tab_2)
        self.btn_show_conf_pas.setGeometry(QtCore.QRect(300, 300, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(8)
        self.btn_show_conf_pas.setFont(font)
        self.btn_show_conf_pas.setStyleSheet("color: #a2a5b6;\n"
                                             "background-color: #25273e;\n"
                                             "border: 0px")
        self.btn_show_conf_pas.setObjectName("btn_show_conf_pas")
        self.btn_show_conf_pas.clicked.connect(lambda: self.show_password_func(3))
        self.btn_sign_up = QtWidgets.QPushButton(parent=self.tab_2)
        self.btn_sign_up.setGeometry(QtCore.QRect(85, 400, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.btn_sign_up.setFont(font)
        self.btn_sign_up.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_sign_up.setStyleSheet("border-radius: 10px;\n"
                                       "text-align: center;\n"
                                       "color: rgb(252, 229, 240);\n"
                                       "background-color: rgb(238, 58, 87)")
        self.btn_sign_up.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.btn_sign_up.setAutoDefault(False)
        self.btn_sign_up.setDefault(False)
        self.btn_sign_up.setObjectName("btn_sign_up")
        self.btn_sign_up.clicked.connect(self.sign_up_check)
        self.btn_show_pas = QtWidgets.QPushButton(parent=self.tab_2)
        self.btn_show_pas.setGeometry(QtCore.QRect(300, 250, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.btn_show_pas.setFont(font)
        self.btn_show_pas.setStyleSheet("color: #a2a5b6;\n"
                                        "background-color: #25273e;\n"
                                        "border: 0px")
        self.btn_show_pas.setObjectName("btn_show_pas")
        self.btn_show_pas.clicked.connect(lambda: self.show_password_func(2))
        self.label_sign_up = QtWidgets.QLabel(parent=self.tab_2)
        self.label_sign_up.setGeometry(QtCore.QRect(20, 40, 181, 80))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(35)
        font.setBold(False)
        font.setWeight(50)
        self.label_sign_up.setFont(font)
        self.label_sign_up.setStyleSheet("color: rgb(202, 204, 213)")
        self.label_sign_up.setObjectName("label_sign_up")
        self.label_ques_2 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_ques_2.setGeometry(QtCore.QRect(60, 560, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.label_ques_2.setFont(font)
        self.label_ques_2.setStyleSheet("color: #b7b9c2")
        self.label_ques_2.setObjectName("label_ques_2")
        self.btn_ques_sign_in = QtWidgets.QPushButton(parent=self.tab_2)
        self.btn_ques_sign_in.setGeometry(QtCore.QRect(240, 560, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.btn_ques_sign_in.setFont(font)
        self.btn_ques_sign_in.setStyleSheet("color: rgb(167, 71, 112);\n"
                                            "background-color: #25273e;\n"
                                            "border: 0px")
        self.btn_ques_sign_in.setObjectName("btn_ques_sign_in")
        self.btn_ques_sign_in.clicked.connect(self.switch_tab)
        self.label_error_tab2 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_error_tab2.setGeometry(QtCore.QRect(30, 116, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Inglobal")
        font.setPointSize(12)
        font.setBold(True)
        self.label_error_tab2.setFont(font)
        self.label_error_tab2.setStyleSheet("color: rgb(204, 118, 120)")
        self.label_error_tab2.setObjectName("label_error")
        self.label_error_tab2.raise_()
        self.line_email.raise_()
        self.line_username_2.raise_()
        self.line_password_2.raise_()
        self.checkBox_agree.raise_()
        self.line_phone.raise_()
        self.btn_sign_up.raise_()
        self.label_sign_up.raise_()
        self.line_confirm_password.raise_()
        self.btn_ques_sign_in.raise_()
        self.label_ques_2.raise_()
        self.btn_show_pas.raise_()
        self.btn_show_conf_pas.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_error_tab.setText(_translate("MainWindow", ""))
        self.label_error_tab2.setText(_translate("MainWindow", ""))
        self.show_pass_1.setText(_translate("MainWindow", "Show"))
        self.label_ques.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.line_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.checkBox_rememb.setText(_translate("MainWindow", "Remember me"))
        self.line_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.btn_forgot.setText(_translate("MainWindow", "Forgot password"))
        self.label_log_in.setText(_translate("MainWindow", "Log In"))
        self.btn_log_in.setText(_translate("MainWindow", "Log In"))
        self.btn_ques_sign_up.setText(_translate("MainWindow", "Sign up"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Log In"))
        self.line_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.line_username_2.setPlaceholderText(_translate("MainWindow", "Username"))
        self.line_password_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.checkBox_agree.setText(_translate("MainWindow", "I agree with privacy and policy"))
        self.btn_show_conf_pas.setText(_translate("MainWindow", "Show"))
        self.line_phone.setPlaceholderText(_translate("MainWindow", "Phone"))
        self.btn_sign_up.setText(_translate("MainWindow", "Sign Up"))
        self.btn_show_pas.setText(_translate("MainWindow", "Show"))
        self.label_sign_up.setText(_translate("MainWindow", "Sign Up"))
        self.label_ques_2.setText(_translate("MainWindow", "Already have an account?"))
        self.line_confirm_password.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.btn_ques_sign_in.setText(_translate("MainWindow", "Sign in"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sign Up"))

    def show_password_func(self, nm):
        if nm == 1:
            if self.cnt_show % 2 == 0:
                self.line_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
                self.cnt_show = 1
            else:
                self.line_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
                self.cnt_show = 0
        elif nm == 2:
            if self.cnt_show1 % 2 == 0:
                self.line_password_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
                self.cnt_show1 = 1
            else:
                self.line_password_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
                self.cnt_show1 = 0
        elif nm == 3:
            if self.cnt_show2 % 2 == 0:
                self.line_confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
                self.cnt_show2 = 1
            else:
                self.line_confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
                self.cnt_show2 = 0

    def switch_tab(self):
        if self.tabWidget.currentIndex() == 0:
            self.tabWidget.setCurrentWidget(self.tab_2)
            self.line_username.clear()
            self.line_password.clear()
            self.checkBox_rememb.setChecked(False)
        else:
            self.tabWidget.setCurrentWidget(self.tab)
            self.line_username_2.clear()
            self.line_phone.clear()
            self.line_email.clear()
            self.line_password_2.clear()
            self.line_confirm_password.clear()
            self.checkBox_agree.setChecked(False)

    def sign_up_check(self):
        user_name, phone, email, password, conf_password = self.line_username_2.text(), self.line_phone.text(), self.line_email.text(), self.line_password_2.text(), self.line_confirm_password.text()
        if '' in [user_name, phone, email, password, conf_password]:
            text = 'Есть незаполненные поля'
        elif user_name.isdigit() or user_name == '' or len(user_name) < 3:
            text = 'Ошибка ввода поля "username"'
        elif not (phone.isdigit()) or len(phone) != 11:
            text = 'Ошибка ввода поля "phone"'
        elif not (fnmatch(email, '?*@?*.?*')):
            text = 'Ошибка ввода поля "email"'
        elif password != conf_password:
            text = 'Пароли не совпадают'
        elif not (self.checkBox_agree.isChecked()):
            text = 'Не стоит галочка согласия'
        else:
            text = sign_up(user_name, phone, email, password)
        if text == 'Успешная регистрация':
            self.label_error_tab2.setStyleSheet("color: rgb(34, 139, 34)")
            self.tabWidget.setCurrentWidget(self.tab)
            self.line_username_2.clear()
            self.line_phone.clear()
            self.line_email.clear()
            self.line_password_2.clear()
            self.line_confirm_password.clear()
            self.checkBox_agree.setChecked(False)

        else:
            self.label_error_tab2.setStyleSheet("color: rgb(204, 118, 120)")
        self.label_error_tab2.setText(text)

    def log_in_check(self):
        user_name, password = self.line_username.text(), self.line_password.text()
        text = log_in(user_name, password)
        if text == 'Успешный вход!':
            self.label_error_tab.setStyleSheet("color: rgb(34, 139, 34)")
            self.line_username.clear()
            self.line_password.clear()
            self.checkBox_rememb.setChecked(False)
        else:
            self.label_error_tab.setStyleSheet("color: rgb(204, 118, 120)")
        self.label_error_tab.setText(text)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
